branches:
  only:
    - master
    - develop
    - /.*appveyor.*/
    - /v.+/

environment:
  nodejs_version: "6.5.0"
  nodejs_arch: "x64"

install:
  - ps: Install-Product node $env:nodejs_version $env:nodejs_arch
  # install modules
  - npm install
  - npm install -g gulp
  - gulp

test_script:
  # run jest
  - npm test

build_script:
  - gulp build-all

artifacts:
  - path: 'out\*.zip'
  - path: 'out\*.exe'

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: fhsM1r5amyUNk2gWNrNSdDEO7idtXAVj7/FubxAogNBADDR8I1zt7tlrXlok2bi+
  draft: true
  force_update: true
  on:
    appveyor_repo_tag: true
